admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"

_sonata_admin:
    resource: .
    type: sonata_admin

_sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'

seo_admin:
    resource: "@VesaxSEOBundle/Admin/Controller"
    type:     annotation

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media