imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    channels: [domain]

    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  rotating_file
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        domain:
            type:  rotating_file
            path:  "%kernel.logs_dir%/domain/%kernel.environment%.log"
            level: info
        console:
            type:  console
        #external:
        #    type:  rotating_file
        #    path:  "%kernel.logs_dir%/external/%kernel.environment%.log"
        #    level: info
        #    channels: [channel_for_external_api_logging_1, channel_for_external_api_logging_2]