app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin:
    resource: "admin_routing.yml"
    prefix: /admin


#Infrastructure
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"